-- BASIC SETUP
---------------

-- warehouse="RETAIL_WH_XS"
-- database="RETAIL_DB",
-- schema="RETAIL_SCHEMA",
-- role="RETAIL_ROLE",

CREATE DATABASE RETAIL_DB;
CREATE SCHEMA RETAIL_DB.RETAIL_SCHEMA;
-- DROP SCHEMA RETAIL_DB.PUBLIC;

CREATE ROLE IF NOT EXISTS RETAIL_ROLE;
-- please apply least privilage principle here.
GRANT ROLE ACCOUNTADMIN TO ROLE RETAIL_ROLE; 

SHOW USERS;

GRANT ROLE RETAIL_ROLE TO USER "QASIMHASSAN";
SHOW GRANTS TO USER "QASIMHASSAN";

USE ROLE RETAIL_ROLE;

GRANT USAGE ON DATABASE RETAIL_DB TO ROLE RETAIL_ROLE;
GRANT USAGE ON SCHEMA RETAIL_DB.RETAIL_SCHEMA TO ROLE RETAIL_ROLE;
GRANT CREATE TABLE ON SCHEMA RETAIL_DB.RETAIL_SCHEMA TO ROLE RETAIL_ROLE;

-- TABLES CREATION
------------------

CREATE TABLE RETAIL_DB.RETAIL_SCHEMA.CUSTOMER_RAW(
    C_BATCH_ID DOUBLE,
    C_CUSTKEY NUMBER(38,0),
    C_NAME VARCHAR(25),
    C_ADDRESS VARCHAR(40),
    C_NATIONKEY NUMBER(38,0),
    C_PHONE VARCHAR(15),
    C_ACCTBAL NUMBER(12,2),
    C_MKTSEGMENT VARCHAR(10),
    C_COMMENT VARCHAR(117)
);

CREATE TABLE RETAIL_DB.RETAIL_SCHEMA.ORDERS_RAW (
    O_BATCH_ID DOUBLE,
    O_ORDERKEY NUMBER(38,0),
    O_CUSTKEY NUMBER(38,0),
    O_ORDERSTATUS VARCHAR(1),
    O_TOTALPRICE NUMBER(12,2),
    O_ORDERDATE DATE,
    O_ORDERPRIORITY VARCHAR(15),
    O_CLERK VARCHAR(15),
    O_SHIPPRIORITY NUMBER(38,0),
    O_COMMENT VARCHAR(79)
);

SELECT * FROM RETAIL_DB.RETAIL_SCHEMA.CUSTOMER_RAW LIMIT 5;
SELECT * FROM RETAIL_DB.RETAIL_SCHEMA.ORDERS_RAW LIMIT 5;


-- VALIDATING BASIC SETUP
-------------------------

USE RETAIL_DB.RETAIL_SCHEMA;
USE ROLE RETAIL_ROLE;

TRUNCATE TABLE RETAIL_DB.RETAIL_SCHEMA.CUSTOMER_RAW;
TRUNCATE TABLE RETAIL_DB.RETAIL_SCHEMA.ORDERS_RAW;

SELECT * FROM RETAIL_DB.RETAIL_SCHEMA.CUSTOMER_RAW LIMIT 5;
SELECT * FROM RETAIL_DB.RETAIL_SCHEMA.ORDERS_RAW LIMIT 5;

 -- creating storage integration
CREATE or replace STORAGE INTEGRATION RETAIL_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::97504693:role/ecommerece-datapipelince-snowflake-role-qh'
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('s3://s3-ecommerece-datapipeline-qh/firehouse/');
  
DESC INTEGRATION RETAIL_S3_INTEGRATION;  

-- creating file format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '')
FIELD_DELIMITER = ','
TRIM_SPACE = TRUE
EMPTY_FIELD_AS_NULL = TRUE;


-- creating external stage
CREATE OR REPLACE STAGE CUSTOMER_RAW_STAGE
  URL='s3://ecommerece-datapipeline-qh/firehose/customers/'
  STORAGE_INTEGRATION = RETAIL_S3_INTEGRATION
  FILE_FORMAT=CSV_FORMAT; 
  
CREATE OR REPLACE STAGE ORDERS_RAW_STAGE
  URL='s3://ecommerece-datapipeline-qh/firehose/orders/'
  STORAGE_INTEGRATION = RETAIL_S3_INTEGRATION
  FILE_FORMAT=CSV_FORMAT;   
  
-- copying data from stage to snowflake table  
COPY INTO RETAIL_DB.RETAIL_SCHEMA.CUSTOMER_RAW (
    C_CUSTKEY,
    C_NAME,
    C_ADDRESS,
    C_NATIONKEY,
    C_PHONE,
    C_ACCTBAL,
    C_MKTSEGMENT,
    C_COMMENT,
    BATCH_ID
) 
FROM (
    SELECT 
        t.$1,
        t.$2,
        t.$3,
        t.$4,
        t.$5,
        t.$6,
        t.$7,
        t.$8,
        '20211114020201'
    FROM @CUSTOMER_RAW_STAGE t
);

-- transformation query
SELECT 
    C.C_NAME AS CUSTOMER_NAME,
    O.O_ORDERDATE AS ORDER_DATE,
    SUM(O.O_TOTALPRICE) AS ORDER_TOTAL_PRICE 
FROM ORDERS_RAW O 
JOIN CUSTOMER_RAW C 
    ON O.O_CUSTKEY = C.C_CUSTKEY
WHERE O_ORDERSTATUS = 'F'
GROUP BY C_NAME, O_ORDERDATE
ORDER BY O_ORDERDATE;

-- command for providing access to role ( aka data governanance)
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_DB.RETAIL_SCHEMA TO ROLE RETAIL_ROLE;

SHOW GRANTS ON SCHEMA RETAIL_DB.RETAIL_SCHEMA;

USE ROLE SECURITYADMIN;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE RETAIL_ROLE;
USE ROLE RETAIL_ROLE;

-- creating transgormed table
CREATE TABLE RETAIL_DB.RETAIL_SCHEMA.ORDER_CUSTOMER_DATE_PRICE (
    CUSTOMER_NAME VARCHAR(25),
    ORDER_DATE DATE,
    ORDER_TOTAL_PRICE NUMBER(12,2),
    BATCH_ID NUMBER
);

-- transformation query used in DAG
INSERT INTO RETAIL_DB.RETAIL_SCHEMA.ORDER_CUSTOMER_DATE_PRICE 
    (CUSTOMER_NAME, ORDER_DATE, ORDER_TOTAL_PRICE, BATCH_ID) 
SELECT 
    C.C_NAME AS CUSTOMER_NAME,
    O.O_ORDERDATE AS ORDER_DATE,
    SUM(O.O_TOTALPRICE) AS ORDER_TOTAL_PRICE,
    C.BATCH_ID
FROM ORDERS_RAW O 
JOIN CUSTOMER_RAW C 
    ON O.O_CUSTKEY = C.C_CUSTKEY 
    AND O.BATCH_ID = C.BATCH_ID
WHERE O_ORDERSTATUS = 'F'
GROUP BY 
    C_NAME,
    O_ORDERDATE,
    C.BATCH_ID
ORDER BY 
    O_ORDERDATE;


-- SNOWSQL SETUP
-------------------------

-- creating PIPE FORMAT
CREATE OR REPLACE FILE FORMAT PIPE_FORMAT_CLI
  TYPE = 'CSV'
  FIELD_DELIMITER = '|'
  SKIP_HEADER = 1;
  
-- creating stage for snowflake
CREATE OR REPLACE STAGE PIPE_CLI_STAGE
  FILE_FORMAT = PIPE_FORMAT_CLI;

--Put customer_detail csv in stage. Snowflake will load the table from this stage
PUT file://C:\<directopry-to-file>\customer_detail.csv @PIPE_CLI_STAGE AUTO_COMPRESS=TRUE;

--List stage to see how nmany files are loaded in stage
LIST @PIPE_CLI_STAGE;

-- copy command to load data into table from stage
COPY INTO customer_detail
  FROM @PIPE_CLI_STAGE
  FILE_FORMAT = (FORMAT_NAME = PIPE_FORMAT_CLI)
  ON_ERROR = 'SKIP_FILE';

-- copy command with pattern if your stage contain multiple files.
COPY INTO mycsvtable
  FROM @my_csv_stage
  FILE_FORMAT = (FORMAT_NAME = mycsvformat)
  PATTERN='.*contacts[1-5].csv.gz'
  ON_ERROR = 'SKIP_FILE';